# Generated by Django 4.0.5 on 2022-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theData',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='workFor',
            field=models.IntegerField(default=0),
        ),
    ]
