# Generated by Django 4.0.5 on 2022-10-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usercodes_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrate',
            name='level',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
