# Generated by Django 4.0.5 on 2022-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payrate_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genCode',
            field=models.BooleanField(default=0),
        ),
    ]
